# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main

pool:
  name: VM-AWS
steps:

- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: '$(ScanCentralURL)'
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscUrl: '$(SSC_URL)'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    uploadToSSC: true
    applicationName: '$(SSC_PROJECTNAME)'
    applicationVersion: '$(SSC_PROJECTVERSION)'
    buildTool: 'none'
    block: true
    outputFile: 'eightball.fpr'
    logFile: 'eightball.log'
    overwrite: true
     
- task: CmdLine@2

  inputs:
    script: 'java -jar C:\fortifytask\fortifytask.jar --sscApplicationUrl=%SSC_URL% --sscAuthToken=%SSC_AUTHTOKEN% --projectName=%SSC_PROJECTNAME% --projectVersionName=%SSC_PROJECTVERSION% --newProject=true --maxSeverityCountLow=0 --maxSeverityCountMedium=0 --maxSeverityCountHigh=0 --maxSeverityCountCritical=0'
    