# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main

pool:
  name: VM-BSB
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      java -jar "C:\fortifytask\fortify-api-client-latest.jar" waitArtifactProcess -n "eightball" -version "eightball-azure";
      $reportfortify = java -jar "C:\fortifytask\fortify-api-client-latest.jar" legacyReport -n "eightball" -version "eightball-azure";
      
      echo $reportfortify;
      
      if ($reportfortify -like ("*- 0 Criticas (Novas)*")){
          Write-Output  "Análise Fortify SAST concluída com sucesso, nenhum problema crítico encontrado."                              
      }
      else{
          Write-Error -Message "Error na  build devido a problemas críticos na análise Fortify SAST." -ErrorAction Stop
      }