# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main

pool:
  name: VM-BSB
steps:

- powershell: |
     Write-Host "##vso[task.setvariable variable=myJobVar]scancentral -sscurl https://34.226.50.182:8443/ssc  -ssctoken 083332a2-ebf2-4453-926d-abbc0b6baf6b  start -bt none  -upload -application "eightball" -version "eightball-azure" -uptoken 083332a2-ebf2-4453-926d-abbc0b6baf6bb"
- powershell: |
     Write-Host "##vso[task.setvariable variable=myOutputJobVar;isoutput=true]this is the same job too"
  name: setOutput
- powershell: |
     Write-Host $(myJobVar) 
- powershell: |
     Write-Host $(setOutput.myOutputJobVar)